force-app/main/default/objects/Grocery_customer__c/Grocery_customer__c.object-meta.xml
<CustomObject>
    <label>Grocery_customer</label>
    <nameField>
        <label>Grocery_customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grocery customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grocery_customer__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total_Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Grocery_Customer__c.field-meta.xml
<CustomField>
    <fullName>Grocery_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grocery_Customer</label>
    <referenceTo>Grocery_Customer__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionTriggerHandler.cls
public with sharing class TransactionTriggerHandler {
    public void onUpdate(List<Transaction__c> trns,Map<ID, Transaction__c> oldTransactionsMap){
        Set<ID> cancelledTrnsId= new Set<ID>();
        List<Transaction__c> closedTransactions= new List<Transaction__c>();
        for(Transaction__c i : trns){
            if(i.Status__c == 'Cancelled' && oldTransactionsMap.get(i.id).Status__c != 'Cancelled'){
                cancelledTrnsId.add(i.Id);
            }
            if(i.Status__c == 'Closed' && i.Grocery_Customer__c != NULL && oldTransactionsMap.get(i.id).Status__c != 'Closed'){
                closedTransactions.add(i);
            }
        }
        List<Line_Item__c> items = [SELECT ID, Quantity__c, Product__c 
                                    FROM Line_Item__c 
                                    WHERE Transaction__c IN :cancelledTrnsId];
        Set<ID> prodsId= new Set<ID>();
        for(Line_Item__c i : items){
            prodsId.add(i.Product__c);
        }
        List<Product__c> prodsToUpdate = [SELECT ID,Available_Amount__c FROM Product__c WHERE ID IN: prodsId];
        for(Integer i = 0;i < prodsToUpdate.size();i++){
            for(Line_Item__c item : items){
                if(prodsToUpdate[i].ID == item.Product__c){
                    prodsToUpdate[i].Available_Amount__c += item.Quantity__c;
                }
            }
        }
        Set<ID> customersId = new Set<ID>();
        for(Transaction__c closedTrn: closedTransactions){
            customersId.add(closedTrn.Grocery_Customer__c);
        }
        Map<Id,Grocery_Customer__c> customersToUpdate = new Map<Id,Grocery_Customer__c>([SELECT id,Total_Amount__c FROM Grocery_Customer__c WHERE ID IN: customersId]); 
        for(Transaction__c customerTrns : closedTransactions){
            customersToUpdate.get(customerTrns.Grocery_Customer__c).Total_Amount__c += customerTrns.Total_Amount__c;
        }
        List<SObject> result = new List<SObject>();
        result.addAll(prodsToUpdate);
        result.addAll(customersToUpdate.values());
        update result;
    }
}