force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/filterValidTransactionsTest.cls
@isTest@isTest
public class filterValidTransactionsTest{
    @testSetup static void testSetup() {
        Integer transactinsNum = 20;
        insert TestDataFactory.generateTransactions(transactinsNum,'Active');
        insert TestDataFactory.generateTransactions(transactinsNum,'Closed');
	}
    @isTest static void validTransactions(){
        Integer transactinsNum = 20;
        List<Transaction__c> testTransactions1 = GroceryServices.filterValidTransactions([SELECT Status__c FROM Transaction__c]);
        for(Transaction__c trans: GroceryServices.filterValidTransactions(testTransactions1)){
            System.assertEquals('Active', trans.Status__c);
        }
    }
    @isTest static void invalidTransactions(){
        Integer transactinsNum = 20;
        List<Transaction__c> testTransactions2 = GroceryServices.filterValidTransactions([SELECT Status__c FROM Transaction__c]);
        for(Transaction__c trans : GroceryServices.filterValidTransactions(testTransactions2)){
            System.assertEquals('Closed', trans.Status__c);
        }
    }
    @isTest static void transactions(){
        for(Transaction__c trans : GroceryServices.filterValidTransactions()){
            System.assertEquals('Closed', trans.Status__c);
        }
    }
}