force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cancelTransactionTest.cls
@isTest
public class CancelTransactionTest {
    @testSetup static void setupTest(){
        Transaction__c testTransaction = new Transaction__c(Status__c = 'Active');
        insert testTransaction;
    }
    @isTest static void cancelTransactionTest(){
        ID testId = [SELECT ID FROM Transaction__c].Id;
        GroceryServices.cancelTransaction(testId);
        Transaction__c result = [SELECT Status__c FROM Transaction__c];
        System.assertEquals('Closed', result.Status__c);
    }
}