force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Calculateable. Total money paid for this product. Cannot use formula since field is used in rollup.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/getTopSellersTest.cls
@isTest
public  class getTopSellersTest {
    @testSetup static void testSetup(){
        List<Transaction__c> setupTransactions = TestDataFactory.generateTransactions(15,'Active');
        List<Product__c> setupProduct = TestDataFactory.generateProducts(3,10,1000);
        Integer daysToAdd = 0;
        insert setupTransactions;
        insert setupProduct;
        List<Line_Item__c> setupItems = new List<Line_item__c>(); 
        for(Product__c prod : setupProduct){
            for(Transaction__c trans : setupTransactions){
                setupItems.addAll(TestDataFactory.generateLineItems(3,5,trans.ID,prod.ID));
            }
        }
        for(Transaction__c trans : setupTransactions){
            Test.setCreatedDate(trans.id, Date.newInstance(2021, 1, 1).addDays(daysToAdd));
            daysToAdd +=15;
        }
        insert setupItems;
    }
    @IsTest static void validYear(){
        Integer testYear = 2021;
        Integer limitNumber = 5;
        Integer offsetNumber = 5;
        List<Line_Item__c> resToTest = [SELECT Product__r.Name, Amount__c
                                        FROM Line_Item__c
                                        WHERE CALENDAR_YEAR(CreatedDate) = :testYear
                                        ORDER BY Amount__c DESC
                                        LIMIT :limitNumber OFFSET :offsetNumber];
        Test.startTest();
        List<Line_Item__c> result = GroceryDAO.getTopSellers(5,5,testYear);
        for(Line_Item__c res1 :result){
            for(Line_Item__c res2 : resToTest){
                system.assertEquals(res2.Amount__c, res1.Amount__c);
            }
        }
        Test.stopTest();
    }
    @IsTest static void invalidYear(){
        Integer testYear = 1000;
        
        Test.startTest();
        List<Line_Item__c> result = GroceryDAO.getTopSellers(5,5,testYear);
        system.assert(result.isEmpty());
            
        Test.stopTest();
    }
    @IsTest static void invalidLimit(){
        Integer testYear = 1000;
        
        Test.startTest();
        List<Line_Item__c> result = GroceryDAO.getTopSellers(0,5,testYear);
        system.assert(result.isEmpty());
            
        Test.stopTest();
    }
    @IsTest static void invalidOffset(){
        Integer testYear = 1000;
        
        Test.startTest();
        List<Line_Item__c> result = GroceryDAO.getTopSellers(5,0,testYear);
        system.assert(result.isEmpty());
            
        Test.stopTest();
    }
}