force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Calculateable. Total money paid for this product. Cannot use formula since field is used in rollup.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IncreaseProductAvailableAmoutBatch.cls
public with sharing class IncreaseProductAvailableAmoutBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        
        return Database.getQueryLocator('SELECT Id, Available_Amount__c FROM  Product__c');
    }
    
    public void execute(Database.BatchableContext bc, List<Product__c> scope){
       	Map<Id, Product__c> productsMap = new Map<Id, Product__c>(scope);
        Date today = date.today();
        Date todayMinus30 = today.addDays(-30);
        List<AggregateResult> totalAmount = [SELECT Product__c, SUM(Amount__c) 
                                             FROM Line_Item__c 
                                             WHERE Product__c IN :productsMap.keyset() AND CreatedDate >=: todayMinus30 AND CreatedDate <=:today
                                             GROUP BY Product__c];
        for(AggregateResult agg :totalAmount){
            if((decimal)agg.get('expr0') > 10000){
                productsMap.get((id)agg.get('Product__c')).Available_Amount__c += 100;
            }
        }
  		update productsMap.values();
       
    }
    
    public void finish(Database.BatchableContext bc){
         
         AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        System.debug(job);

    }
}