force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Calculateable. Total money paid for this product. Cannot use formula since field is used in rollup.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GroceryServices.cls
public class GroceryServices{
    /*
    Method filterValidTransactions returns Active and Closed transactions from a list of Transaction__c
    Input parameter: (List<Transaction__c> transactions)
    Result: (List<Transaction__c> transactions) - transactions with Active and Closed Status
     */
    public static List<Transaction__c> filterValidTransactions(List<Transaction__c> transactions) {
        if(transactions.isEmpty())
        {
            return new List<Transaction__c>();
        } 
        List<Transaction__c> validTrs = new List<Transaction__c>();
        for(Transaction__c trs : transactions){
            if(trs.Status__c == 'Active' || trs.Status__c == 'Closed') validTrs.add(trs);
        }
        return validTrs;
    }
    public static List<Transaction__c> filterValidTransactions() {
        return [SELECT ID,Status__c
                FROM Transaction__c 
                WHERE Status__c LIKE 'Active' OR Status__c LIKE'Closed'];
    }
    /*
    Create method calculateTotalAmount in GroceryServices class which returns total amount for all specified Line Items
    Input parameter: (List<Line_Item__c> lineItems)
    Result: Integer amount - total amount for all specified Line Items
     */
    public static Integer calculateTotalAmount()
    {	
        Line_Item__c[] items = [SELECT Amount__c FROM Line_Item__c];
        Decimal  res = 0;
        for(Line_Item__c i : items){
        res += i.Amount__c;
        }
        return (Integer)res;
    }
    public static Integer calculateTotalAmount(List<Line_Item__c> items){
        Decimal  res = 0;
        for(Line_Item__c i : items){
        res += i.Amount__c;
        }
        return (Integer)res;
    }
}