force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/getNumberOfSoldProductsTest.cls
@isTest
public class GetNumberOfSoldProductsTest {
    @testSetup static void testSetup(){
        List<Transaction__c> setupTransactions = TestDataFactory.generateTransactions(15,'Active');
        List<Product__c> setupProduct = TestDataFactory.generateProducts(3,10,1000);
        Integer daysToAdd = 0;
        insert setupTransactions;
        insert setupProduct;
        List<Line_Item__c> setupItems = new List<Line_item__c>(); 
        for(Product__c prod : setupProduct){
            for(Transaction__c trans : setupTransactions){
                setupItems.addAll(TestDataFactory.generateLineItems(3,5,trans.ID,prod.ID));
            }
        }
        insert setupItems;
        for(Transaction__c trans : setupTransactions){
            Test.setCreatedDate(trans.id, Date.newInstance(2021, 1, 1).addDays(daysToAdd));
            daysToAdd +=15;
        }
        
    }
    @isTest static void validDates(){
        
        Date startDate = Date.newInstance(2021, 2, 1);
        Date endDate = Date.newInstance(2021, 4, 1);
        List<AggregateResult> items = [SELECT Product__c, COUNT(id)
                                       FROM Line_Item__c
                                       WHERE Transaction__r.CreatedDate > :startDate AND Transaction__r.CreatedDate <:endDate
                                       GROUP BY Product__c];
        Map<ID, Integer>resToTest = new Map<ID, Integer>();
        for(AggregateResult item :items){
            resToTest.put((ID)item.get('Product__c'),(Integer)item.get('expr0'));
        }
        Test.startTest();
        Map<Id,Integer> result = GroceryDAO.getNumberOfSoldProducts(startDate, endDate);
        for(Id resId : result.keySet()){
            system.debug('resToTest ' + resToTest.get(resId));
            system.debug(' result '+result.get(resId));
            System.assertEquals(resToTest.get(resId), result.get(resId));
        }
        Test.stopTest();

    }
    @isTest static void invalidlDates(){
        Date startDate = Date.newInstance(2021, 4, 1);
        Date endDate = Date.newInstance(2021, 2, 1);
        Map<ID, Integer>resToTest = new Map<ID, Integer>();
        Map<Id,Integer> result = GroceryDAO.getNumberOfSoldProducts(startDate, endDate);
        System.assertEquals(resToTest,result);
        
    }
    @isTest static void equalDates(){
        Date startDate = Date.newInstance(2021, 2, 1);
        Date endDate = Date.newInstance(2021, 2, 1);
        Map<ID, Integer>resToTest = new Map<ID, Integer>();
        Map<Id,Integer> result = GroceryDAO.getNumberOfSoldProducts(startDate, endDate);
        System.assertEquals(resToTest,result);
    }

}