force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LineItemTriggerHandler.cls
public with sharing class LineItemTriggerHandler {
    //Each Line Item should decrease the Product's Available Amount. Prevent values less than 0.
    public void onInsert(List<Line_Item__c> newItems) {
        Set<ID> prodsId= new Set<ID>();
        for(Line_Item__c i : newItems){
            prodsId.add(i.Product__c);
        }
        List<Product__c> prods = [SELECT ID, Available_Amount__c FROM Product__c WHERE ID IN: prodsId];
        List<Product__c> newProds = new List<Product__c>();
        for(Product__c i : prods){
            for(Line_Item__c j : newItems){
                if(j.Product__c == i.ID){
                    if(i.Available_Amount__c-j.Quantity__c>=0){
                    	newProds.add(new Product__c(ID = i.ID, Available_Amount__c = i.Available_Amount__c-j.Quantity__c));
                    } else{
                        j.Quantity__c.addError('Quantity of line item cannot be greater than product amount');
                    }
                }
          
            }
        }
        update newProds;
    }
    public void onUpdate(List<Line_Item__c> newItems,Map<ID, Line_Item__c> oldItemsMap) {
        Set<ID> prodsId= new Set<ID>();
        for(Line_Item__c i : newItems){
            prodsId.add(i.Product__c);
        }
        List<Product__c> prods = [SELECT ID, Available_Amount__c FROM Product__c WHERE ID IN: prodsId];
		List<Product__c> newProds = new List<Product__c>();
        for(Product__c i : prods){
            for(Line_Item__c j : newItems){
                if(j.Product__c == i.ID){
                    if(i.Available_Amount__c-j.Quantity__c+oldItemsMap.get(j.ID).Quantity__c >= 0){
                        newProds.add(new Product__c(ID = i.ID, Available_Amount__c= i.Available_Amount__c-j.Quantity__c+oldItemsMap.get(j.ID).Quantity__c));
    
                    } else{
                        j.Quantity__c.addError('Quantity of line item cannot be greater than product amount');
                    }
                }
          
            }
        }
        update newProds;
    }
}