force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Calculateable. Total money paid for this product. Cannot use formula since field is used in rollup.</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Item__c/fields/Product_Name_With_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_With_Code__c</fullName>
    <formula>Product__r.Name +&quot; (&quot;+Product__r.Code__c+&quot;)&quot;</formula>
    <label>Product Name With Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Item Code</description>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price for one item</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>Visa, MasterCard</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active, Closed, Cancelled, Archived</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GroceryDAO.cls
public class GroceryDAO {
    //return map, where key = product id, value = number of sold items in period between start/end dates. Date value is Transaction's CreatedDate
    public static Map<ID,Integer>getNumberOfSoldProducts(DateTime startDate, DateTime endDate){
        if(endDate == startDate||startDate>endDate) {
            return new Map<ID,Integer>();
        }
        List<AggregateResult> items = [SELECT Product__c, COUNT(id)
                                       FROM Line_Item__c
                                       WHERE Transaction__r.CreatedDate > :startDate AND Transaction__r.CreatedDate <:endDate
                                       GROUP BY Product__c]; 
        Map<ID, Integer>res = new Map<ID, Integer>();
        for(AggregateResult i :items){
            res.put((ID)i.get('Product__c'),(Integer)i.get('expr0'));
        }
        return res;
    }
    //return map, where key = transaction id, value = amount of money of all line items related to this trasaction.
    
    public static Map<ID,Decimal> getTotalAmountOfTransactions(Set<Id> trsIds){
        if(trsIds.isEmpty()) {
            return new Map<ID,Decimal>();
        }
        List<Transaction__c> trs = [SELECT ID, Total_Amount__c FROM Transaction__c WHERE ID IN: trsIds];
        Map<ID,Decimal> res = new Map<ID,Decimal>();
        for(Transaction__c i: trs){
            res.put(i.ID, i.Total_Amount__c);
        }
        return res;
    }
    //return  10 most profitable transactions (based on "total amount")
    @AuraEnabled
    public static List<Transaction__c> getMostProfitableTransactions(){
        return [SELECT ID,Name, Total_Amount__c, Status__c, CreatedDate 
                FROM Transaction__c
                WHERE Status__c IN ('Active','Closed')
                ORDER BY Total_Amount__c DESC
                LIMIT 10]; 
    }
    //get top sold products of specified year. Ordered by - most seller at top.
    public static List<Line_Item__c> getTopSellers(Integer limitNumber, Integer offsetNumber, Integer year){
        if(limitNumber <1|| offsetNumber<1) {
            return new List<Line_Item__c>();
        }
        return [SELECT Product__r.Name, Amount__c
                FROM Line_Item__c
                WHERE CALENDAR_YEAR(CreatedDate) = :year
                ORDER BY Amount__c DESC
               	LIMIT :limitNumber OFFSET:offsetNumber];
    }
     //how many products where bought with visa/masatercard? return result, groupped by payment type
    public static List<AggregateResult> getPaymentStatisticsAmount(){
        return [SELECT Payment_Type__c, COUNT(id)
                FROM Transaction__c
                GROUP BY Payment_Type__c];
    }
    //get all products
    public static List<Product__c> getProducts(Integer limitNumber, Integer offsetNumber){
        if(limitNumber <1|| offsetNumber<1) {
            return new List<Product__c>();
        }
        return [SELECT Name, Code__c, Price__c, Available_Amount__c 
                FROM Product__c 
                LIMIT :limitNumber OFFSET :offsetNumber];
    }
    //get all products with Available_Amount__c> 0
    public static List<Product__c> getProductAvailableInStore(Integer limitNumber, Integer offsetNumber ){
        if(limitNumber <1|| offsetNumber<1) {
            return new List<Product__c>();
        }
        return [SELECT Name, Code__c, Price__c, Available_Amount__c 
                FROM Product__c 
                WHERE Available_Amount__c > 0
                LIMIT :limitNumber OFFSET :offsetNumber];
    }
    //get all line items related to inputed transaction
    @AuraEnabled
    public static List<Line_Item__c> getLineItemsByTransaction(ID transactionId){
       return [SELECT ID, Name, Product_Name_With_Code__c, Quantity__c, Amount__c 
               FROM Line_Item__c 
               WHERE Transaction__c =:transactionId];
    }
 
}