force-app/main/default/objects/Line_Item__c/Line_Item__c.object-meta.xml
<CustomObject>
    <description>Details about each Product that was purchased during Transaction</description>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>only product can be added with positive Available_Amount__c</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Available_Amount__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>Item in store</description>
    <label>Product_c</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Available_Amount__c.field-meta.xml
<CustomField>
    <fullName>Available_Amount__c</fullName>
    <description>Amount of items, available in store</description>
    <label>Available Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price for one item</description>
    <label>Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>Information about the purchase</description>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IncreaseProductAvailableAmoutBatchTest.cls
@isTest
public class IncreaseProductAvailableAmoutBatchTest {
    @testSetup static void testSetup(){
        List<sObject> testRecords = new List<sObject>();
        Product__c testProd = new Product__c(Price__c = 1000, Available_Amount__c = 50000);
        testRecords.add(testProd);
        Transaction__c testTransaction= new Transaction__c();
        testRecords.add(testTransaction);
        insert testRecords;
       	List<Line_Item__c> testItems = new List<Line_Item__c>();
        for(Integer i = 0; i < 12; i++){
             testItems.add(new Line_Item__c(Quantity__c = 1000,Product__c = testProd.id, Transaction__c = testTransaction.id)); 
        }
        insert testItems;
        for(Line_Item__c item : testItems){
            Test.setCreatedDate(item.id, Date.newInstance(2021, 10, 25));
        }
        
        
    }
    @isTest static void increaseAvailableAmountTest(){
        test.startTest();
        String jobId = Database.executeBatch(new IncreaseProductAvailableAmoutBatch());
        System.assertEquals(38000, [SELECT Available_Amount__c FROM Product__c WHERE Price__c = 1000].Available_Amount__c);
        system.debug('Expected: 38000 Real: '+[SELECT Available_Amount__c FROM Product__c WHERE Price__c = 1000].Available_Amount__c);
        test.stopTest();
        System.assertEquals(38100, [SELECT Available_Amount__c FROM Product__c WHERE Price__c = 1000].Available_Amount__c);
        system.debug('Expected: 38100 Real: '+[SELECT Available_Amount__c FROM Product__c WHERE Price__c = 1000].Available_Amount__c);
    }

}